name: Publish Docs

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish Docs Site
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v5

      - name: ğŸ“¦ Enable Corepack
        run: corepack enable

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: yarn

      - name: ğŸ“¦ Install dependencies
        working-directory: ./iac
        run: yarn install --immutable

      - name: ğŸ”„ Pulumi Up
        uses: pulumi/actions@v6
        with:
          stack-name: prod
          command: up
          work-dir: ./iac
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}